# Patterns for files that should NEVER appear in the prompt.
# These are auto-generated by Android tooling and carry zero
# semantic value for a commit message.

EXCLUDE_PATTERNS = [
    "R.java",
    "R2.java",
    "BuildConfig.java",
    "BuildConfig.kt",
    "databinding/",
    "DataBindingInfo",
    "build/",
    ".idea/",
    ".iml",
    "gradlew",
    "gradlew.bat",
    "gradle/wrapper/",
    "local.properties",
    "google-services.json",
    "**/generated/**",
    "generated/",
    ".gradle/",
    "captures/",
    "__pycache__/",
    ".DS_Store",
]


def is_excluded(filepath):
    """Return True if this file should be completely excluded."""
    for pattern in EXCLUDE_PATTERNS:
        # Strip glob stars for simple substring matching
        clean = pattern.replace("**/", "").replace("**", "")
        if clean in filepath:
            return True
    return False


def filter_files(file_map):
    """
    Split file_map into (kept, removed).
    kept   → files worth including in the prompt
    removed → junk/generated files that were stripped
    """
    kept = {}
    removed = {}

    for path, diff in file_map.items():
        if is_excluded(path):
            removed[path] = diff
        else:
            kept[path] = diff

    return kept, removed
